### ISSUE TITLE
hyperf-admin 和 hyperf-admin-frontend 不在同一个域名下的时候，报 CORS error。

### ISSUE THREAD

**Issue by simonkuang** [hyperf-admin/hyperf-admin-frontend#11]
> Access to XMLHttpRequest at 'http://1.2.3.4:9501/user/login' from origin 'http://admin.abcdefg.com' has been blocked by CORS policy: Request header field x-token is not allowed by Access-Control-Allow-Headers in preflight response.

报上面的错。

**Comment by simonkuang** [comment]
期望在 Access-Control-Allow-Headers 中加上 `X-Token` 这个值，允许 `X-Token` 这个头的传输。

**Comment by daodao97** [comment]
这个可以修改配置 `'cors.allow_headers'` 节点来自定义`header`信息, [源码](https://github.com/hyperf-admin/hyperf-admin/blob/master/src/base-utils/src/Middleware/CorsMiddleware.php#L18)
