### ISSUE TITLE
安装前端后，页面出现 Cannot find module 

### ISSUE THREAD

**Issue by huanghuag** [hyperf-admin/hyperf-admin-frontend#15]
![image](https://user-images.githubusercontent.com/33785106/135740805-e6eb4f47-66dd-44bb-aaa9-8aa1e0c30914.png)

**Comment by daodao97** [comment]
不要用cnpm安装依赖，请使用npm或yarn，并用官方源重新安装依赖

**Comment by huanghuag** [comment]
可以了，谢谢
